language: python
python:
  - '2.7'
  - '3.4'
services:
  - elasticsearch
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=parent_swap[dev]
script:
  - python setup.py test
sudo: false